#:schema node_modules/wrangler/config-schema.json
name = "miraibo-go"
compatibility_date = "2024-10-11"
main = "./build/worker/index.js"
assets = { directory = "./build/client" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
